-- 테이블 생성 --
DROP TABLE PERSONS;
DROP TABLE JOBS;
DROP SEQUENCE PERSON_PNO_SQ;

CREATE TABLE JOBS(  -- JOBS 테이블 생성 
    JNO NUMBER(2,0) PRIMARY KEY,
    JNAME VARCHAR2(20) UNIQUE 
);
CREATE SEQUENCE PERSON_PNO_SQ MAXVALUE 99999 NOCACHE NOCYCLE; -- 시퀀스 생성
CREATE TABLE PERSONS(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(50),
    JNO NUMBER(2,0) REFERENCES JOBS(JNO) NOT NULL,
    KOR NUMBER(3) CHECK( KOR BETWEEN 0 AND 100),
    ENG NUMBER(3) CHECK( ENG BETWEEN 0 AND 100),
    MAT NUMBER(3) CHECK( MAT BETWEEN 0 AND 100)
);
SELECT * FROM JOBS;
SELECT * FROM PERSONS;

INSERT INTO JOBS VALUES (10, '유튜버');
INSERT INTO JOBS VALUES (20, '가수');
INSERT INTO JOBS VALUES (30, '배우');

INSERT INTO PERSONS VALUES (PERSON_PNO_SQ.NEXTVAL, '아이유', 20, 100, 90, 95);
INSERT INTO PERSONS VALUES (PERSON_PNO_SQ.NEXTVAL, '이지금', 10, 100, 95, 90);
INSERT INTO PERSONS VALUES (PERSON_PNO_SQ.NEXTVAL, '안성훈', 20, 99, 95, 91);
INSERT INTO PERSONS VALUES (PERSON_PNO_SQ.NEXTVAL, '박재정', 20, 80, 90, 100);
COMMIT;