-- 프로그램에 쓸 쿼리
SELECT JNAME FROM JOBS;
-- 1번 수행시 입력가능한 직업명 
INSERT INTO PERSONS VALUES (PERSON_PNO_SQ.NEXTVAL, '홍홍홍', (SELECT JNO FROM JOBS WHERE JNAME = '배우'), 90, 90, 90);
COMMIT;
-- 2번 기능 : JNAME 입력받아, RANK, PNAME(PNO), JNAME, KOR, ENG, MAT, SUM출력
SELECT PNAME ||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSONS P, JOBS J
    WHERE P.JNO = J.JNO
    ORDER BY SUM DESC; -- 서브쿼리
SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME ||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
        FROM PERSONS P, JOBS J
        WHERE P.JNO = J.JNO AND JNAME = '배우'
        ORDER BY SUM DESC) A;
-- 3번 기능 : RANK, PNAME(PNO), JNAME, KOR, ENG, MAT, SUM 출력
SELECT ROWNUM RANK, A.*
    FROM (SELECT PNAME ||'('||PNO||')' PNAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSONS P, JOBS J
    WHERE P.JNO = J.JNO
    ORDER BY SUM DESC) A;
    COMMIT;
    