-- [VIII] Sequence : 순차번호 생성기. 대부분 인위적인 PRIMARY KEY(PK) 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
  START WITH 1 -- 1부터 시작 
  INCREMENT BY 1 -- 1씩 증가
  MAXVALUE 9999  -- 최대값
  MINVALUE  1  -- 최소값
  NOCACHE
  NOCYCLE; 
  -- NOCACHE, NOCYCLE, MAXVALUE 자주사용
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값
  DROP SEQUENCE FRIEND_SEQ; -- 시퀀스 삭제
  CREATE SEQUENCE FRIEND_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
  DROP TABLE FRIEND;
  CREATE TABLE FRINED(
  NO NUMBER(5) PRIMARY KEY, -- 시퀀스를 사용해서 값이 들어갈 필드
  NAME VARCHAR2(30) NOT NULL,
  TEL VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(255),
  LAST_MODIFY DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울 서대문'); -- 몇번 실행가능
SELECT * FROM FRIEND;

-- INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
--    VALUES (FRIEND_SEQ.NEXTVAL, NULL, '서울 마포'); -- 에러

-- EX. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST-SEQ 시퀀스를 생성하고 시퀀스를 사용하시오
    CREATE SEQUENCE TEST_SEQ
    START WITH 101 
    MAXVALUE 999999 
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 시퀀스 사용전에는 현재값을 조회할 수 없음
SELECT TEST_SEQ.NEXTVAL FROM DUAL; -- 시퀀스 사용

-- EX. 시퀀스 NO_SEQ 초기값 1부터 999까지 1씩 증가하는 사용 :
    -- SYSDATE의 'RRMMDD' 추출 => '230728' || 시퀀스 생성수(100) -> '100'
DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
SELECT TO_CHAR(SYSDATE, 'RRMMDD' ) FROM DUAL;
SELECT TO_CHAR(NO_SEQ.NEXTVAL, '000') FROM DUAL; -- 005
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || TO_CHAR(NO_SEQ.NEXTVAL, '000') FROM DUAL; -- 230728 005
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || TRIM(TO_CHAR(NO_SEQ.NEXTVAL, '000')) NO FROM DUAL; -- 230728005

--  ★ 과제물 ★
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL(
LEVELNO NUMBER(3) PRIMARY KEY,
LEVELNAME VARCHAR2(20) NOT NULL
);
SELECT * FROM MEMBER_LEVEL;

CREATE TABLE MEMBER(
mNO NUMBER(3) PRIMARY KEY,
mNAME VARCHAR2(20) NOT NULL,
mPW VARCHAR2(8),
mEMAIL VARCHAR2(20) UNIQUE,
mPOINT NUMBER(4) CHECK (mPOINT >= 0),
mRDATE DATE DEFAULT SYSDATE,
LEVELNO NUMBER(3) REFERENCES MEMBER_LEVEL(LEVELNO)
);

SELECT * FROM MEMBER;

-- MEMBER_LEVEL 값 입력 --
INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반고객');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버고객');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드고객');

-- 시퀀스 값 -- 
DROP SEQUENCE MEMBER_MNO_SEQ;
CREATE SEQUENCE MEMBER_MNO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;

-- MEMBER 값 입력 --
INSERT INTO MEMBER VALUES (MEMBER_MNO_SEQ.NEXTVAL,
                                '홍길동', 'aa', 'hong@hong.com', 0, '22/03/10', 0);

INSERT INTO MEMBER VALUES (MEMBER_MNO_SEQ.NEXTVAL,
                                '신길동', 'bb', 'sin@sin.com', 1000, '22/04/01', 1);

SELECT mNO, mNAME, mRDATE, mEMAIL, mPOINT, LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;
