-- ☆ ☆ ☆ 과제물 ☆ ☆ ☆
DROP TABLE MEMBERS;
DROP TABLE CART;
DROP TABLE ORDERS;
DROP TABLE ORDERDETAIL;
DROP TABLE PRODUCT;

-- MEMBERS 테이블 생성 --
CREATE TABLE MEMBERS(
    mID VARCHAR2(30) PRIMARY KEY NOT NULL,
    mNAME VARCHAR2(30) UNIQUE,
    mADDR VARCHAR2(255),
    mTEL VARCHAR2(255),
    mEMAIL VARCHAR2(30) NOT NULL
);

-- MEMBERS 내용 기입 --
INSERT INTO MEMBERS VALUES ('abc', '홍길동', '서울시 서대문구 대현동', '010-9999-9999', 'hong@hong.com');
INSERT INTO MEMBERS VALUES ('def', '김김동', '경기도 수원시', '010-8888-8888', 'kim@kim.com');
SELECT * FROM MEMBERS;

-- CART 테이블 생성 --
DROP TABLE CART;
CREATE TABLE CART(
    cNO NUMBER(3) PRIMARY KEY,
    mID VARCHAR2(30) REFERENCES MEMBERS(mID),
    pCODE VARCHAR2(20)  REFERENCES PRODUCT(pCODE),
    QTY NUMBER(4),
    COST NUMBER(10)
);
SELECT * FROM CART;
-- CART 시퀀스 생성 --
DROP SEQUENCE CARTB_SEQ;
CREATE SEQUENCE CARTB_SEQ MAXVALUE 999999999 NOCACHE;
-- CART 내용 기입 --
SELECT * FROM CART;
INSERT INTO CART VALUES
  (CARTB_SEQ.NEXTVAL, 'abc', 'A1', 3, (SELECT PRICE FROM PRODUCT WHERE PCODE='A1')*3);
INSERT INTO CART VALUES
  (CARTB_SEQ.NEXTVAL, 'abc', 'B1', 1, (SELECT PRICE FROM PRODUCT WHERE PCODE='B1')*1);


-- ORDERS 테이블 생성 --

CREATE TABLE ORDERS(
    oNO NUMBER(4) PRIMARY KEY,
    mID VARCHAR2(20) REFERENCES MEMBERS(mID),
    oNAME VARCHAR2(20) UNIQUE,
    oADDR VARCHAR2(30),
    oTEL NUMBER(10),
    oDATE DATE DEFAULT SYSDATE
);
SELECT * FROM ORDERS;
-- OREDERS 내용 주입 --
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 999 NOCACHE;
INSERT INTO ORDERS (oNO, mID, oNAME, oADDR, oTEL) VALUES (TO_CHAR(SYSDATE, 'RR/MM/DD') || TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000')), 'abc', 
            '홍길동', '서울시 서대문구', '010-9999-9999');
-- ORDERDETAIL 테이블 생성
CREATE TABLE ORDERDETAIL(
    oNO NUMBER(4) REFERENCES ORDERS(oNO),
    pCODE NUMBER(4) REFERENCES PRODUCT(pCODE),
    QTV NUMBER(4),
    COST NUMBER(4)
);
SELECT * FROM ORDERDETAIL;

-- PRODUCT 테이블 생성 --
CREATE TABLE PRODUCT(
    pCODE VARCHAR2(20) PRIMARY KEY,
    pNAME VARCHAR2(20),
    PRICE NUMBER(10),
    STOCK NUMBER(10)
    );
SELECT * FROM PRODUCT;

-- PRODUCT 내용 주입 --
INSERT INTO PRODUCT VALUES ('A1', '맥주', 3000, 100);
INSERT INTO PRODUCT VALUES ('A2', '마스크', 200, 100);
INSERT INTO PRODUCT VALUES ('B1', '땅콩', 3000, 100);
INSERT INTO PRODUCT VALUES ('B2', '오징어', 5000, 100);
INSERT INTO PRODUCT VALUES ('C1', '소독약', 7000, 100);