DROP TABLE REVIEW;
DROP SEQUENCE REVIEW_SEQ;
CREATE TABLE REVIEW(
    RID NUMBER(4) PRIMARY KEY,
    RNAME VARCHAR2(50) NOT NULL,
    RTITLE VARCHAR2(50) NOT NULL, --제목
    RCONTENT VARCHAR2(1000), --본문
    REMAIL VARCHAR2(100), --메일주소
    RHIT NUMBER(7) DEFAULT 0 NOT NULL, --조회수
    RPW VARCHAR2(50) NOT NULL, --비밀번호
    RGROUP NUMBER(5) NOT NULL, --글그룹
    RSTEP NUMBER(5) NOT NULL, -- 같은그룹내 출석순서
    RINDENT NUMBER(5) NOT NULL,   -- 글 LIST출력시 글 제목 들여쓰기 정도(원글 0)
    RIP VARCHAR2(50) NOT NULL, -- 글쓰기를 요청한 컴퓨터의 IP주소
    RRDATE DATE DEFAULT SYSDATE NOT NULL -- 글 작성 시점
);
SELECT * FROM REVIEW;
CREATE SEQUENCE REVIEW_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
-- 더미 데이터 추가
INSERT INTO REVIEW
    (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '세준', '글1', '안녕', NULL, '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.5.4');
INSERT INTO REVIEW
    (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '가연', '글2', '어서와', NULL, '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.5.9');
INSERT INTO REVIEW
    (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '만웰', '글3', '반가워', NULL, '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.5.0');
INSERT INTO REVIEW
    (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '선우', '글4', '행복한 하루', NULL, '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.5.7');
INSERT INTO REVIEW
    (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '솔우', '글5', '즐거운 하루', NULL, '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.5.5');
    
UPDATE REVIEW SET RHIT = 1111 WHERE RID=1; -- 조회수 조작
---- DAO에 쓸 SQL
---- 1. 글목록(전체 글 그룹이 최신글이 위로)
SELECT * FROM REVIEW ORDER BY RGROUP DESC;
---- 1. 글목록(startRow부터 endRow까지 리스트)
SELECT * FROM REVIEW ORDER BY RGROUP DESC; -- 출력 기준
SELECT ROWNUM RN, A.* 
  FROM (SELECT * FROM REVIEW ORDER BY RGROUP DESC) A; -- TOP-N구문 전단계
SELECT *
  FROM ( SELECT ROWNUM RN, A.* 
         FROM (SELECT * FROM REVIEW ORDER BY RGROUP DESC) A )
  WHERE RN BETWEEN 1 AND 3; -- TOP-N구문 (DAO에 들어갈 QUERY)
        
        
-- 2. 전체 글 갯수
SELECT COUNT(*) CNT FROM REVIEW;
-- 3. 원글쓰기 - 작성자, 글제목, 본문, 이메일, 비번, IP (BGROUP은 글번호, BSTEP은 0, BINDENT는 0)
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RHIT, RPW, RGROUP, RSTEP, RINDENT, RIP)
    VALUES (REVIEW_SEQ.NEXTVAL, '솔우', '글5', '즐거운 하루', 'LA@NAVER.COM', '111', '111', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.4.5');
-- 4. bID로 조회수 1 올리기 (글상세보기시 필요)
UPDATE REVIEW SET RHIT = RHIT + 1 WHERE RID=1;
-- 5. bID로 DTO가져오기(글수정FORM, 답변글쓰기FORM)
SELECT * FROM REVIEW WHERE RID=1;
-- 6. 글수정 (작성자, 글제목, 본문, 이메일, 비번, IP 수정)
UPDATE REVIEW
  SET RNAME = '홍길동',
      RTITLE = '바꾼제목',
      RCONTENT = '바꾼본문',
      REMAIL = 'H@H.COM',
      RPW    = '111',
      RIP    = '127.0.0.1'
  WHERE RID=1;
-- 7. 글삭제(비번을 맞게 입력한 경우만 삭제)
COMMIT;
DELETE FROM REVIEW WHERE RID=1 AND RPW='111';
ROLLBACK;
SELECT * FROM REVIEW ORDER BY RGROUP DESC;

-- 8. 답글 달기 관련 더미데이터
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '박', '글3', '냉무', NULL, '111', REVIEW_SEQ.CURRVAL, 0, 0, '127.0.0.1');
SELECT * FROM REVIEW ORDER BY RGROUP DESC, RSTEP;
-- 글1-1
-- ⓐ단계(답변글 쓰기 전 BSTEP 조정단계)
UPDATE REVIEW SET RSTEP = RSTEP + 1 WHERE RGROUP=1 AND RSTEP>0;
-- 답변글 INSERT
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '윤', '글1-1', '냉무', NULL, '111', 1, 1, 1, '127.0.0.1');
SELECT * FROM REVIEW ORDER BY RGROUP DESC, RSTEP;
-- 글2-1
-- ⓐ단계(답변글 쓰기 전 BSTEP 조정단계)
UPDATE REVIEW SET RSTEP=RSTEP+1 WHERE RGROUP=2 AND RSTEP>0;
-- 답변글 INSERT
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '이', '글2-1', '냉무', NULL, '111', 2, 1, 1, '127.0.0.1');
-- 글2-2
-- ⓐ단계(답변글 쓰기 전 BSTEP 조정단계)
UPDATE REVIEW SET RSTEP=RSTEP+1 WHERE RGROUP=2 AND RSTEP>0;
-- 답변글 INSERT
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '허', '글2-2', '냉무', NULL, '111', 2, 1, 1, '127.0.0.1');
SELECT * FROM REVIEW ORDER BY RGROUP DESC, RSTEP; -- 확인

-- 글2-2-1 (글6의 답변글)
SELECT * FROM REVIEW WHERE RID=6; -- 원글 정보(BGROUP, BSTEP, BINDENT)
-- ⓐ단계(답변글 쓰기 전 BSTEP 조정단계)
UPDATE REVIEW SET RSTEP = RSTEP + 1 WHERE RGROUP=2 AND RSTEP>1;
-- 답변글 INSERT
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '장', '글2-2-1', '냉무', NULL, '111', 2, 2, 2, '127.0.0.1');
SELECT * FROM REVIEW ORDER BY RGROUP DESC, RSTEP;

-- DAO에 들어갈 QUERY
-- 1. 글목록에서 ORDER BY 부분 추가
SELECT *
  FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM REVIEW ORDER BY RGROUP DESC, RSTEP) A)
  WHERE RN BETWEEN 2 AND 4; 
  
-- 8. ⓐ단계(답변글 쓰기 전 BSTEP 조정단계)
UPDATE REVIEW SET RSTEP = RSTEP + 1 WHERE RGROUP=2 AND RSTEP>1;
-- 9. 답변글 INSERT
INSERT INTO REVIEW (RID, RNAME, RTITLE, RCONTENT, REMAIL, RPW, RGROUP, RSTEP, RINDENT, RIP)
  VALUES (REVIEW_SEQ.NEXTVAL, '장', '글2-2-1', '냉무', NULL, '111', 2, 2, 2, '127.0.0.1');
  
COMMIT;